name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Change to your main branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package application
        run: |
          zip -r my-fastapi-app.zip .  # Adjust the command as needed

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          application_name: github-actionsdemo
          environment_name: Github-actionsdemo-env
          version_label: ${{ github.sha }}
          region: ap-south-1  # Change to the correct region
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          deployment_package: my-fastapi-app.zip
          existing_bucket_name: asgdemo
